name: Build and Deploy Jekyll and Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - uses: actions/jekyll-build-pages@v1
        with:
          destination: "./output"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./output"

  spring-boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
      - run: ./mvnw clean package
      - uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar
